/*
 * スキー予約サービス
 *
 * このサービスはスキーのサポートをするため、スキー場、スキー場の天気、スキー場のホテル、ホテルの予約などの機能を提供する。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() DefaultAPIServicer {
	return &DefaultAPIService{}
}

// ResortsGet - スキー場の一覧を取得する。
func (s *DefaultAPIService) ResortsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ResortsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Object{}) or use other options such as http.Ok ...
	// return Response(200, []Object{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ResortsGet method not implemented")
}

// ResortsResortIdHotelsGet - スキー場のホテル一覧を取得する。
func (s *DefaultAPIService) ResortsResortIdHotelsGet(ctx context.Context, resortId string) (ImplResponse, error) {
	// TODO - update ResortsResortIdHotelsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Object{}) or use other options such as http.Ok ...
	// return Response(200, []Object{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ResortsResortIdHotelsGet method not implemented")
}

// ResortsResortIdHotelsHotelIdBookingsPut - ホテルの予約をとる。
func (s *DefaultAPIService) ResortsResortIdHotelsHotelIdBookingsPut(ctx context.Context, resortId string, hotelId string, booking Booking) (ImplResponse, error) {
	// TODO - update ResortsResortIdHotelsHotelIdBookingsPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Booking{}) or use other options such as http.Ok ...
	// return Response(200, Booking{}), nil

	// TODO: Uncomment the next line to return response Response(404, Message{}) or use other options such as http.Ok ...
	// return Response(404, Message{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ResortsResortIdHotelsHotelIdBookingsPut method not implemented")
}
