/*
 * スキー予約サービス
 *
 * このサービスはスキー場一覧、スキー場のホテルの一覧、スキー場のホテルに予約することできます。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// DefaultAPIController binds http requests to an api service and writes the service results to the http response
type DefaultAPIController struct {
	service DefaultAPIServicer
	errorHandler ErrorHandler
}

// DefaultAPIOption for how the controller is set up.
type DefaultAPIOption func(*DefaultAPIController)

// WithDefaultAPIErrorHandler inject ErrorHandler into controller
func WithDefaultAPIErrorHandler(h ErrorHandler) DefaultAPIOption {
	return func(c *DefaultAPIController) {
		c.errorHandler = h
	}
}

// NewDefaultAPIController creates a default api controller
func NewDefaultAPIController(s DefaultAPIServicer, opts ...DefaultAPIOption) Router {
	controller := &DefaultAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultAPIController
func (c *DefaultAPIController) Routes() Routes {
	return Routes{
		"ResortsGet": Route{
			strings.ToUpper("Get"),
			"/v1/resorts",
			c.ResortsGet,
		},
		"ResortsResortIdHotelsGet": Route{
			strings.ToUpper("Get"),
			"/v1/resorts/{p_resortId}/hotels",
			c.ResortsResortIdHotelsGet,
		},
		"ResortsResortIdHotelsHotelIdBookingsOrderNoDelete": Route{
			strings.ToUpper("Delete"),
			"/v1/resorts/{p_resortId}/hotels/{p_hotelId}/bookings/{p_orderNo}",
			c.ResortsResortIdHotelsHotelIdBookingsOrderNoDelete,
		},
		"ResortsResortIdHotelsHotelIdBookingsOrderNoPut": Route{
			strings.ToUpper("Put"),
			"/v1/resorts/{p_resortId}/hotels/{p_hotelId}/bookings/{p_orderNo}",
			c.ResortsResortIdHotelsHotelIdBookingsOrderNoPut,
		},
		"ResortsResortIdHotelsHotelIdBookingsPost": Route{
			strings.ToUpper("Post"),
			"/v1/resorts/{p_resortId}/hotels/{p_hotelId}/bookings",
			c.ResortsResortIdHotelsHotelIdBookingsPost,
		},
	}
}

// ResortsGet - スキー場の一覧を取得する。
func (c *DefaultAPIController) ResortsGet(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ResortsGet(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ResortsResortIdHotelsGet - スキー場のホテル一覧を取得する。
func (c *DefaultAPIController) ResortsResortIdHotelsGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	pResortIdParam, err := parseNumericParameter[int32](
		params["p_resortId"],
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.ResortsResortIdHotelsGet(r.Context(), pResortIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ResortsResortIdHotelsHotelIdBookingsOrderNoDelete - ホテルの予約を取り消しする。
func (c *DefaultAPIController) ResortsResortIdHotelsHotelIdBookingsOrderNoDelete(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	pResortIdParam, err := parseNumericParameter[int32](
		params["p_resortId"],
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	pHotelIdParam, err := parseNumericParameter[int32](
		params["p_hotelId"],
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	pOrderNoParam := params["p_orderNo"]
	if pOrderNoParam == "" {
		c.errorHandler(w, r, &RequiredError{"p_orderNo"}, nil)
		return
	}
	result, err := c.service.ResortsResortIdHotelsHotelIdBookingsOrderNoDelete(r.Context(), pResortIdParam, pHotelIdParam, pOrderNoParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ResortsResortIdHotelsHotelIdBookingsOrderNoPut - ホテルの予約を変更する。
func (c *DefaultAPIController) ResortsResortIdHotelsHotelIdBookingsOrderNoPut(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	pResortIdParam, err := parseNumericParameter[int32](
		params["p_resortId"],
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	pHotelIdParam, err := parseNumericParameter[int32](
		params["p_hotelId"],
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	pOrderNoParam := params["p_orderNo"]
	if pOrderNoParam == "" {
		c.errorHandler(w, r, &RequiredError{"p_orderNo"}, nil)
		return
	}
	bookingParam := Booking{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bookingParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBookingRequired(bookingParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBookingConstraints(bookingParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ResortsResortIdHotelsHotelIdBookingsOrderNoPut(r.Context(), pResortIdParam, pHotelIdParam, pOrderNoParam, bookingParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ResortsResortIdHotelsHotelIdBookingsPost - ホテルの予約をとる。
func (c *DefaultAPIController) ResortsResortIdHotelsHotelIdBookingsPost(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	pResortIdParam, err := parseNumericParameter[int32](
		params["p_resortId"],
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	pHotelIdParam, err := parseNumericParameter[int32](
		params["p_hotelId"],
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	bookingParam := Booking{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bookingParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBookingRequired(bookingParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBookingConstraints(bookingParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ResortsResortIdHotelsHotelIdBookingsPost(r.Context(), pResortIdParam, pHotelIdParam, bookingParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
