/*
 * スキー予約サービス
 *
 * このサービスはスキーのサポートをするため、スキー場、スキー場の天気、スキー場のホテル、ホテルの予約などの機能を提供する。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Booking struct {

	// 取れた予約の内部ID
	Id int32 `json:"id,omitempty"`

	// お客様問い合わせ用注文番号
	OrderId string `json:"orderId,omitempty"`

	BookingGuest Guest `json:"bookingGuest,omitempty"`

	// 同行者情報
	AdditionalGuests []BookingAdditionalGuestsInner `json:"additionalGuests,omitempty"`
}

// AssertBookingRequired checks if the required fields are not zero-ed
func AssertBookingRequired(obj Booking) error {
	if err := AssertGuestRequired(obj.BookingGuest); err != nil {
		return err
	}
	for _, el := range obj.AdditionalGuests {
		if err := AssertBookingAdditionalGuestsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertBookingConstraints checks if the values respects the defined constraints
func AssertBookingConstraints(obj Booking) error {
	return nil
}
