/*
 * スキー予約サービス
 *
 * このサービスはスキー場一覧、スキー場のホテルの一覧、スキー場のホテルに予約することできます。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Guest struct {

	// 名前
	Name string `json:"name"`

	// 性別
	Gender string `json:"gender"`

	// 年齢
	Age int32 `json:"age"`
}

// AssertGuestRequired checks if the required fields are not zero-ed
func AssertGuestRequired(obj Guest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"gender": obj.Gender,
		"age": obj.Age,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGuestConstraints checks if the values respects the defined constraints
func AssertGuestConstraints(obj Guest) error {
	return nil
}
