/*
 * スキー予約サービス
 *
 * このサービスはスキー場一覧、スキー場のホテルの一覧、スキー場のホテルに予約することできます。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Hotel struct {

	// ホテルの内部ID、このIDを使って、ホテルを操作できる。
	Id int32 `json:"id,omitempty"`

	// ホテル名称
	Name string `json:"name,omitempty"`

	// ホテルの住所
	Address string `json:"address,omitempty"`

	// ホテル電話番号
	TelNo string `json:"telNo,omitempty"`
}

// AssertHotelRequired checks if the required fields are not zero-ed
func AssertHotelRequired(obj Hotel) error {
	return nil
}

// AssertHotelConstraints checks if the values respects the defined constraints
func AssertHotelConstraints(obj Hotel) error {
	return nil
}
