/*
 * スキー予約サービス
 *
 * このサービスはスキーのサポートをするため、スキー場、スキー場の天気、スキー場のホテル、ホテルの予約などの機能を提供する。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Resort struct {

	// スキー場の内部ID、このIDを使って、このスキー場に関連する操作を行える。
	Id int32 `json:"id,omitempty"`

	// スキー場の名称
	Name string `json:"name,omitempty"`

	// スキー場の住所
	Address string `json:"address,omitempty"`

	// スキー場の天気状況、0番目は本日の天気、1番目は昨日の天気、2番目は一昨日の天気。。。。
	Weather []ResortWeatherInner `json:"weather,omitempty"`
}

// AssertResortRequired checks if the required fields are not zero-ed
func AssertResortRequired(obj Resort) error {
	for _, el := range obj.Weather {
		if err := AssertResortWeatherInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertResortConstraints checks if the values respects the defined constraints
func AssertResortConstraints(obj Resort) error {
	return nil
}
