/*
 * スキー予約サービス
 *
 * このサービスはスキー場一覧、スキー場のホテルの一覧、スキー場のホテルに予約することできます。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Guest struct {

	// 名前
	Name string `json:"name,omitempty"`

	// 性別
	Gender string `json:"gender,omitempty"`

	// 年齢
	Age int32 `json:"age,omitempty"`
}

// AssertGuestRequired checks if the required fields are not zero-ed
func AssertGuestRequired(obj Guest) error {
	return nil
}

// AssertGuestConstraints checks if the values respects the defined constraints
func AssertGuestConstraints(obj Guest) error {
	return nil
}
