/*
 * スキー予約サービス
 *
 * このサービスはスキー場一覧、スキー場のホテルの一覧、スキー場のホテルに予約することできます。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ResortWeatherInner struct {

	// 天気状況（雨、晴れ、雪、曇り）
	Weather string `json:"weather,omitempty"`

	// 風のスピード
	WindSpeed int32 `json:"windSpeed,omitempty"`

	// 雪の厚さ、CM単位
	SnowDepth int32 `json:"snowDepth,omitempty"`
}

// AssertResortWeatherInnerRequired checks if the required fields are not zero-ed
func AssertResortWeatherInnerRequired(obj ResortWeatherInner) error {
	return nil
}

// AssertResortWeatherInnerConstraints checks if the values respects the defined constraints
func AssertResortWeatherInnerConstraints(obj ResortWeatherInner) error {
	return nil
}
