/*
 * スキー予約サービス
 *
 * このサービスはスキー場一覧、スキー場のホテルの一覧、スキー場のホテルに予約することできます。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type BookingAdditionalGuestsInner struct {

	// 名前
	Name string `json:"name,omitempty"`

	// 性別
	Gender string `json:"gender,omitempty"`

	// 年齢
	Age int32 `json:"age,omitempty"`

	RelationShip string `json:"relationShip,omitempty"`
}

// AssertBookingAdditionalGuestsInnerRequired checks if the required fields are not zero-ed
func AssertBookingAdditionalGuestsInnerRequired(obj BookingAdditionalGuestsInner) error {
	return nil
}

// AssertBookingAdditionalGuestsInnerConstraints checks if the values respects the defined constraints
func AssertBookingAdditionalGuestsInnerConstraints(obj BookingAdditionalGuestsInner) error {
	return nil
}
